import { adminPanelState } from './admin-panel.types';

export const initialState: adminPanelState = {
	yugiohCardTypes: [
		'Agua',
		'Beast',
		'Beast-Warrior',
		'Cyberse',
		'Dinosaur',
		'Divine-Beast',
		'Dragon',
		'Effect',
		'Fairy',
		'Fiend',
		'Fish',
		'Fusion',
		'Insect',
		'Link',
		'Machine',
		'Pendulum',
		'Plant',
		'Psychic',
		'Pyro',
		'Reptile',
		'Ritual',
		'Rock',
		'Sea Serpent',
		'Spellcaster',
		'Thunder',
		'Tuner',
		'Warrior',
		'Winged Beast',
		'Wyrm',
		'Zombie',
	],
	yugiohCardAttributes: [
		'Air',
		'Dark',
		'Divine',
		'Earth',
		'Fire',
		'Light',
		'Water',
		'Wind',
	],
	yugiohCardRarities: [
		'Common',
		'Duel Terminal',
		'Ghost Rare',
		'Gold Rare',
		'Parallel',
		'Prismatic Secret Rare',
		'Rare',
		'Secret Rare',
		'Super Rare',
		'Ultimate Rare',
		'Ultra Rare',
	],
	isSubmmiting: false,
	yugiohEditable: null,
	isModalInventoryOpen: false,
	isFetchingData: true,
	yugiohInventory: [],
	navItems: [
		{
			label: 'Ordenes',
			children: [
				{
					label: 'Por clientes',
					//subLabel: "Ordenes por clientes",
					href: '/panel-admin/client-panel',
				},
				{
					label: 'Por Ordenes individuales',
					//subLabel: "Ordenes por ordenes individuales",
					href: '/panel-admin/orders-panel',
				},
			],
		},
		{
			label: 'Inventarios',
			children: [
				{
					label: 'Yu-Gi-Oh! TCG',
					//åsubLabel: "Módulo de administración cartas",
					href: '/panel-admin/inventory?tcg=yugioh',
				},
				// {
				// 	label: "Pokémon TCG",
				// 	subLabel: "Módulo de administración cartas de Pokémon TCG.",
				// 	href: "#",
				// },
				// {
				// 	label: "Magic: The Gathering",
				// 	subLabel: "Módulo de administración cartas de Magic: The Gathering.",
				// 	href: "#",
				// },
			],
		},
	],
	clientList: [],
	clientOrders: [],
	clientData: null,
};
